apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: namespace1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  namespace: namespace1
  labels:
    app: wordpress
    tier: frontend
  annotations:
    function-AddLabel: "Fn::AddLabel(pod/wordpress-pod, MysqlCluster:namespace1.cluster1)"
spec:
  containers:
  - image: wordpress:4.8-apache
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: Fn::ImportValue(MysqlCluster:namespace1.cluster1:Service(filter=master))
    - name: WORDPRESS_DB_PASSWORD
      value: mypass
    ports:
    - containerPort: 80
      name: wordpress
    volumeMounts:
    - name: wordpress-persistent-storage
      mountPath: /var/www/html
  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: namespace1
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP

