apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubeplus-deployment
  labels:
    app: kubeplus
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: kubeplus
  template:
    metadata:
      labels:
        app: kubeplus
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      - name: operator-manager
        image: operator-manager:latest
        imagePullPolicy: Never
        command: [ "/operator-manager"]
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      - name: operator-deployer
        image: operator-deployer:latest
        imagePullPolicy: Never
        command: [ "/operator-deployer"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operators.operatorcontroller.kubeplus
spec:
  group: operatorcontroller.kubeplus
  version: v1
  names:
    kind: Operator
    plural: operators
  scope: Namespaced
