apiVersion: platformapi.kubeplus/v1alpha1
kind: WordpressStack 
metadata:
  name: tenant1 
spec:
  namespace: wp-stack-ns1 
  # Change this value appropriately for your setup
  nodeName: gke-cluster-4-default-pool-dacc3ab3-1x4v
