apiVersion: platformapi.kubeplus/v1alpha1
kind: WordpressStack 
metadata:
  name: tenant1 
spec:
  namespace: wp-stack-ns1 
  # Change this value appropriately for your setup
  nodeName: gke-cluster-2-default-pool-b3a56a0d-3dxx

