---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-example-crt
spec:
  secretName: cert-example-crt
  dnsNames:
  - www.moodle1.net
  commonName: www.moodle1.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.moodle1.net
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
