apiVersion: moodlecontroller.kubeplus/v1
kind: Moodle
metadata:
  name: moodletest
spec:
  plugins: ["profilecohort"]
  mySQLServiceName: Fn::ImportValue(MysqlCluster:default.cluster1:Service(filter=master))
  mySQLUserName: Fn::ImportValue(MysqlCluster:default.cluster1:StatefulSet.mountPath(filter=/etc/mysql))
  mySQLUserPassword: cluster1-secret.ROOT_PASSWORD #Fn::ImportValue(Secret:default.cluster1-secret.data.ROOT_PASSWORD)
  moodleAdminEmail: Fn::ImportValue(MysqlCluster:default.cluster1:Service)


# mySQLServiceName: Fn::ImportValue(MysqlCluster:default.cluster1:StatefulSet.mountPath)
# mySQLServiceName: Fn::ImportValue(MysqlCluster:default.cluster1:annotations:exports/op2) # cluster1-mysql-master
# mySQLServiceName: Fn::ImportValue(crd:mysqlclusters.mysql.presslabs.org:annotations:platform-as-code/outputs:service)
# Deployment.spec.template.spec.containers.volumeMounts.mountPath
# mySQLServiceName: Fn::ImportValue(MysqlCluster:default.cluster1:Deployment.mountPath)

