apiVersion: moodlecontroller.kubeplus/v1
kind: Moodle
metadata:
  name: moodletest
spec:
  plugins: ["profilecohort"]
  mySQLServiceName: Fn::ImportValue(MysqlCluster:default.cluster1:Service(filter=master))
  mySQLUserName: Fn::ImportValue(MysqlCluster:default.cluster1:StatefulSet.mountPath(filter=/etc/mysql))
  mySQLUserPassword: cluster1-secret.ROOT_PASSWORD #Fn::ImportValue(Secret:default.cluster1-secret.data.ROOT_PASSWORD)
  moodleAdminEmail: Fn::ImportValue(MysqlCluster:default.cluster1:Service)
