apiVersion: v1
kind: Secret
metadata:
  name: webhook-tls-certificates
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeplus:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeplus 
  namespace: default
  apiGroup: ""
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubeplus
  namespace: default
---
kind: Service
apiVersion: v1
metadata:
  name: kubeplus
spec:
  selector:
    app: kubeplus
  type: NodePort 
  ports:
  - protocol: TCP
    port: 90
    targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: crd-hook-service
  labels:
    app: crd-hook-service
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: kubeplus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeplus-deployment # do not change
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeplus
  template:
    metadata:
      name: kubeplus
      labels:
        app: kubeplus
    spec:
      serviceAccount: kubeplus
      initContainers:
      - name: webhook-cert-setup
        # This is a minimal kubectl image based on Alpine Linux that signs certificates using the k8s extension api server
        image: gcr.io/cloudark-kubeplus/webhook-tls-getter:0.0.8
        imagePullPolicy: Always
        env:
          - name: KUBEPLUS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command: ["./webhook-create-signed-cert-new.sh"]
        args:
          - "--service"
          - "crd-hook-service"
          - "--namespace"
          - "$(KUBEPLUS_NAMESPACE)"
          - "--secret"
          - "webhook-tls-certificates"
      containers:
      - name: crd-hook
        image: gcr.io/cloudark-kubeplus/pac-mutating-admission-webhook:0.5.9
        imagePullPolicy: Always
        args:
          - -tlsCertFile=/etc/webhook/certs/cert.pem
          - -tlsKeyFile=/etc/webhook/certs/key.pem
          - -alsologtostderr
          #- -v=4
          - 2>&1
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      - name: mutating-webhook-helper
        image: gcr.io/cloudark-kubeplus/mutating-webhook-helper:0.2.0 
        imagePullPolicy: Always
      - name: platform-operator
        image: gcr.io/cloudark-kubeplus/platform-operator:0.0.10
        imagePullPolicy: Always
        command: [ "/platform-operator"]
      - name: helmer
        image: gcr.io/cloudark-kubeplus/helm-pod:0.0.10
        imagePullPolicy: Always
        command: ["/root/helm-pod"]
        volumeMounts:
        - mountPath: /chart
          name: chart-volume
      volumes:
        - name: chart-volume
          emptyDir: {}
        - name: webhook-certs
          secret:
            secretName: webhook-tls-certificates
