apiVersion: v1
kind: Secret
metadata:
  name: webhook-tls-certificates
  namespace: openshift-operators
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubeplus
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeplus:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeplus 
  namespace: openshift-operators
  apiGroup: ""
---
