apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeplus 
  template:
    metadata:
      labels:
        app: kubeplus 
    spec:
      serviceAccountName: kubeplus
      containers:
        - name: mutating-webhook-helper
          image: lmecld/mutating-webhook-helper:latest
          imagePullPolicy: IfNotPresent
        - name: discovery-server
          image: lmecld/kubediscovery:latest
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: discovery-service
spec:
  selector:
    app: kubeplus 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  type: ClusterIP 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeplus:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeplus 
  namespace: default
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubeplus
  namespace: default 
---
