apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: platform-as-code.crd-binding
  labels:
    app: crd-hook
webhooks:
  - name: platform-as-code.crd-binding.v1
    clientConfig:
      service:
        name: crd-hook-service
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU1VT1A3cWZnWXZxYWRpcXlBbGRqQ013RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pURmtNVFU0TmpVdE1UWTNOQzAwTkdVeExUZ3lOREF0Wm1Ga1pqY3hPRGs1TURVegpNQjRYRFRJd01ETXhPREUwTXpjMU9Gb1hEVEkxTURNeE56RTFNemMxT0Zvd0x6RXRNQ3NHQTFVRUF4TWtaVEZrCk1UVTROalV0TVRZM05DMDBOR1V4TFRneU5EQXRabUZrWmpjeE9EazVNRFV6TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBakZsTEVlM0ljVXkwUnhRTVY2RXh2cmZyRmg1aEdpMzIzT1N0T3NIeQpKWWM5Z0crbnFCNUJ5b3NjTlpoelJtdTF4aUtuS0pla1A5Rll3TDEwTW83bUZrME45bk9NcUZGVnQyTlExQ2pMCjZQbU9ZQ3NEUFp1VGxLNzRBdE5raWFPY24vUEpsVEtqeldHKzRyOGJxdXlrbmxLZHo5Z2c5aVFYbnp5TVZnV3YKK2llcjdJeTc0MHQzSENBdEljQzFLMWtEdVlYL2FlRlJ5R3czVTFQR2FBN25NYmlkM0pvMU1qa240UUpEWDVrSQozclZNaElRcVRlc0JvSDdkUFFDRmtjUzNvdlowbU9YKytQWU1XaStpMUl2clFNM0dWYzVxVVVBdURNYXBhOUdFCjk3VGRFeU5jUXdVY0p5U3RmYW5TNWZiZFYyUWxQTDBpNlZ4bDdiTWJHOGQ5NXdJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpnUitJc2Q4ejJEYzRQdUZ3ZlZzeThDdzVvY2Z3Q1IvRXM1VS94VUhmZjRTWDVmWk1Cd1U0WjJRTW1HUFRTdTZDClFndDBvM01DVXZudlpaQXRxUmd5SldTQ2pGejdUMCtURGF4S0phRGFHcEdiYW9TNXNsQS9JMlRJczhGcStobzIKNVlhQmZEdWVkU2JFY2k1aW5MaURzSHFRRHpBSlBCelFxNmROU3phaWtSekRrY0g1czJSQ3duYlNiVlovWlpndQpYNnd0MVFpNSsvNnlHWlVscExwa1o5NnRiOHc4bHZrTUYwUHplMG9OUEJrOTJGUzNIS09iTGFrRFBsZy9TYUN5CmRvZXM5VFNQQlpaTkRRVkFOYitWUGtLMEdlZzhKcVdOYXJkM2VyUktHZkxRRjVkSkd3T3VYbFMyWUNjdGdZbnEKOUZiUjBrOXBuSTI3ZkkzRFRIKzVlUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["workflows.kubeplus", "apps", "extensions", ""]
        apiVersions: ["v1alpha1", "v1", "v1beta1"]
        resources: ["resourcepolicies", "deployments", "statefulsets", "replicasets", "daemonsets", "replicationcontrollers", "pods"]
