apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: moodle-restic
  labels:
    stack: moodle1-stack
  annotations:
    pac/actions: Fn::AddLabel(app/moodle1, Moodle:default.moodle1:Deployment)
spec:
  selector:
    matchLabels:
      app: moodle1
  fileGroups:
  - path: Fn::ImportValue(Moodle:default.moodle1:Deployment.mountPath(filter=moodledata))
    retentionPolicyName: 'keep-last-10'
  backend:
    s3:
      endpoint: 's3.amazonaws.com'
      bucket: mysqlcluster
      prefix: stash1
    storageSecretName: Fn:ImportValue(Secret:default.s3-secret)
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: Fn::ImportValue(Moodle:default.moodle1:Deployment.mountPath(filter=moodledata))
    name: moodle-data
  retentionPolicies:
  - name: 'keep-last-10'
    keepLast: 10
    prune: true
