---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: moodle1-cert
labels:
  use-route53-solver: "true"
spec:
  secretName: moodle1-cert
  issuerRef:
    name: moodle1
    kind: Issuer
  commonName: www.moodle1.net
  dnsNames:
  - www.moodle1.net
  acme:
    config:
    - dns01:
        provider: moodle1-dns
      domains:
      - www.moodle1.net
