apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: my-data-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-central1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
