apiVersion: moodlecontroller.kubeplus/v1
kind: Moodle
metadata:
  name: moodle2
  annotations:
    function-AddLabel: "Fn::AddLabel(application/moodle2, MysqlCluster:default.cluster1:Service(filter=master))"
  labels:
    stack: moodle2-stack
spec:
  plugins: ["profilecohort"]
  mySQLServiceName: Fn::ImportValue(MysqlCluster:default.cluster1:Service(filter=master))
  mySQLUserName: root
  mySQLUserPassword: cluster1-secret.ROOT_PASSWORD 
  moodleAdminEmail: test@test.com
