apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: bXlwYXNz
