apiVersion: workflows.kubeplus/v1alpha1
kind: ResourcePolicy 
metadata:
  name: mysqlcluster-policy
spec:
  resource:
    kind: MysqlCluster
    group: mysql.presslabs.org
    version: v1alpha1
  policy:
    podresources:
      limits:
        cpu: 200m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 2Gi
