apiVersion: workflows.kubeplus/v1alpha1
kind: ResourceComposition
metadata:
  name: tenantservice 
spec:
  # newResource defines the new CRD to be installed define a workflow.
  newResource:
    resource:
      kind: Tenant 
      group: platformapi.kubeplus
      version: v1alpha1
      plural: tenants
    # URL of the Helm chart that contains Kubernetes resources that represent a workflow.
    chartURL: https://github.com/cloud-ark/operatorcharts/blob/master/teamresources-0.0.1.tgz?raw=true
    chartName: teamresources
  # respolicy defines the resource policy to be applied to instances of the specified custom resource.
  respolicy:
    apiVersion: workflows.kubeplus/v1alpha1
    kind: ResourcePolicy 
    metadata:
      name: tenant-policy
    spec:
      resource:
        kind: Tenant
        group: platformapi.kubeplus
        version: v1alpha1
      policy:
        # Add following requests and limits for the first container of all the Pods that will be deployed
        # in the Namespace defined in the Helm chart
        podconfig:
          scope: Namespace
          limits:
            cpu: 200m
            memory: 4Gi
          requests:
            cpu: values.cpurequests # Take cpurequests as input from Tenant resource instance spec
            memory: values.memoryrequests # Take memoryrequests as input from Tenant resource instance spec
