apiVersion: workflows.kubeplus/v1alpha1
kind: ResourceMonitor
metadata:
  name: mysqlcluster-monitor
spec:
  resource:
    kind: MysqlCluster
    group: mysql.presslabs.org
    version: v1alpha1
  monitorRelationships: ownerReference
