---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
  namespace: ingress-basic
spec:
  secretName: tls-secret
  dnsNames:
  - www.moodle1.net
  commonName: www.moodle1.net
  acme:
    config:
    - dns01:
        provider: prod-s3
      domains:
      - www.moodle1.net
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
