apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: platformworkflows.workflows.kubeplus
spec:
  group: workflows.kubeplus
  version: v1alpha1
  names:
    kind: PlatformWorkflow
    plural: platformworkflows
  scope: Namespaced
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubeplus-platformoperator
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: platform-operator
  template:
    metadata:
      labels:
        app: platform-operator
    spec:
      containers:
      - name: platform-operator
        image: lmecld/platform-operator:0.0.4-alpha2
        imagePullPolicy: Always
        command: [ "/platform-operator"]

