apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-operator-deployment
  labels:
    app: postgres-operator
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      containers:
      - name: postgres-crd-v2
        image: lmecld/postgres-crd-v2:latest
        imagePullPolicy: Always
        command: [ "/postgres-crd-v2"]
