apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: moodle2
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: devdatta@cloudark.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: moodle2-tls-secret
    # Enable the HTTP-01 challenge provider
    http01: {}
